name: Vavoo Otomatik Guncelleme

on:
  schedule:
    - cron: '0 3 * * *' # Her gün saat 03:00'te çalışır
  workflow_dispatch: # Manuel çalıştırmak istersen buton çıkarır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install requests

      - name: Botu Çalıştır
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python vavoo_bot.py
        
